/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,jsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "primary":                    "rgb(var(--c-primary) / <alpha-value>)",
        "primary-container":          "rgb(var(--c-primary-container) / <alpha-value>)",
        "primary-fixed":              "rgb(var(--c-primary-fixed) / <alpha-value>)",
        "primary-fixed-dim":          "#b2c5ff",
        "on-primary":                 "#ffffff",
        "on-primary-container":       "rgb(var(--c-on-primary-container) / <alpha-value>)",
        "on-primary-fixed":           "#001848",
        "on-primary-fixed-variant":   "#0040a2",
        "secondary":                  "#1b6d24",
        "secondary-container":        "rgb(var(--c-secondary-container) / <alpha-value>)",
        "secondary-fixed":            "#a3f69c",
        "secondary-fixed-dim":        "#88d982",
        "on-secondary":               "#ffffff",
        "on-secondary-container":     "rgb(var(--c-on-secondary-container) / <alpha-value>)",
        "on-secondary-fixed":         "#002204",
        "on-secondary-fixed-variant": "#005312",
        "tertiary":                   "#6c3300",
        "tertiary-container":         "#904600",
        "tertiary-fixed":             "#ffdcc6",
        "tertiary-fixed-dim":         "#ffb786",
        "on-tertiary":                "#ffffff",
        "on-tertiary-container":      "#ffc7a3",
        "on-tertiary-fixed":          "#311300",
        "on-tertiary-fixed-variant":  "#723600",
        // Surface colors → CSS variables (dark mode aware)
        "surface":                    "rgb(var(--c-surface) / <alpha-value>)",
        "surface-dim":                "rgb(var(--c-surface-dim) / <alpha-value>)",
        "surface-bright":             "rgb(var(--c-surface-bright) / <alpha-value>)",
        "surface-variant":            "rgb(var(--c-surface-variant) / <alpha-value>)",
        "surface-container-lowest":   "rgb(var(--c-surface-c0) / <alpha-value>)",
        "surface-container-low":      "rgb(var(--c-surface-clow) / <alpha-value>)",
        "surface-container":          "rgb(var(--c-surface-c) / <alpha-value>)",
        "surface-container-high":     "rgb(var(--c-surface-chigh) / <alpha-value>)",
        "surface-container-highest":  "rgb(var(--c-surface-chighest) / <alpha-value>)",
        "surface-tint":               "#0c56d0",
        "on-surface":                 "rgb(var(--c-on-surface) / <alpha-value>)",
        "on-surface-variant":         "rgb(var(--c-on-surface-variant) / <alpha-value>)",
        "background":                 "rgb(var(--c-background) / <alpha-value>)",
        "on-background":              "rgb(var(--c-on-background) / <alpha-value>)",
        "outline":                    "rgb(var(--c-outline) / <alpha-value>)",
        "outline-variant":            "rgb(var(--c-outline-variant) / <alpha-value>)",
        "error":                      "#ba1a1a",
        "error-container":            "#ffdad6",
        "on-error":                   "#ffffff",
        "on-error-container":         "#93000a",
        "inverse-surface":            "rgb(var(--c-inverse-surface) / <alpha-value>)",
        "inverse-on-surface":         "rgb(var(--c-inverse-on-surface) / <alpha-value>)",
        "inverse-primary":            "#b2c5ff",
      },
      fontFamily: {
        headline: ["Manrope", "sans-serif"],
        body:     ["Public Sans", "sans-serif"],
        label:    ["Public Sans", "sans-serif"],
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg:      "0.5rem",
        xl:      "0.75rem",
        "2xl":   "1rem",
        "3xl":   "1.5rem",
        full:    "9999px",
      },
    },
  },
  plugins: [],
}
