/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,jsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "primary":                    "#003d9b",
        "primary-container":          "#0052cc",
        "primary-fixed":              "#dae2ff",
        "primary-fixed-dim":          "#b2c5ff",
        "on-primary":                 "#ffffff",
        "on-primary-container":       "#c4d2ff",
        "on-primary-fixed":           "#001848",
        "on-primary-fixed-variant":   "#0040a2",
        "secondary":                  "#1b6d24",
        "secondary-container":        "#a0f399",
        "secondary-fixed":            "#a3f69c",
        "secondary-fixed-dim":        "#88d982",
        "on-secondary":               "#ffffff",
        "on-secondary-container":     "#217128",
        "on-secondary-fixed":         "#002204",
        "on-secondary-fixed-variant": "#005312",
        "tertiary":                   "#6c3300",
        "tertiary-container":         "#904600",
        "tertiary-fixed":             "#ffdcc6",
        "tertiary-fixed-dim":         "#ffb786",
        "on-tertiary":                "#ffffff",
        "on-tertiary-container":      "#ffc7a3",
        "on-tertiary-fixed":          "#311300",
        "on-tertiary-fixed-variant":  "#723600",
        "surface":                    "#f8f9fa",
        "surface-dim":                "#d9dadb",
        "surface-bright":             "#f8f9fa",
        "surface-variant":            "#e1e3e4",
        "surface-container-lowest":   "#ffffff",
        "surface-container-low":      "#f3f4f5",
        "surface-container":          "#edeeef",
        "surface-container-high":     "#e7e8e9",
        "surface-container-highest":  "#e1e3e4",
        "surface-tint":               "#0c56d0",
        "on-surface":                 "#191c1d",
        "on-surface-variant":         "#434654",
        "background":                 "#f8f9fa",
        "on-background":              "#191c1d",
        "outline":                    "#737685",
        "outline-variant":            "#c3c6d6",
        "error":                      "#ba1a1a",
        "error-container":            "#ffdad6",
        "on-error":                   "#ffffff",
        "on-error-container":         "#93000a",
        "inverse-surface":            "#2e3132",
        "inverse-on-surface":         "#f0f1f2",
        "inverse-primary":            "#b2c5ff",
      },
      fontFamily: {
        headline: ["Manrope", "sans-serif"],
        body:     ["Public Sans", "sans-serif"],
        label:    ["Public Sans", "sans-serif"],
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg:      "0.5rem",
        xl:      "0.75rem",
        "2xl":   "1rem",
        "3xl":   "1.5rem",
        full:    "9999px",
      },
    },
  },
  plugins: [],
}
